version: '3.8'

services:
  postgresdb:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=appsecret
      - POSTGRES_DB=appdb
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  config-api-migrate:
    image: victorpabon88/config-api:latest
    networks:
      - app_net
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
    secrets:
      - database_url
    command: ["alembic", "upgrade", "head"]
    depends_on:
      - service_healthy
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: on-failure

  config-api:
    image: victorpabon88/config-service-api:latest
    networks:
      - app_net
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - APP_ENVIRONMENT=production
    secrets:
      - database_url
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - config-api-migrate
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

secrets:
  database_url:
    file: ./database_url.txt

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfssrv01,rw"
      device: ":/data/docker-vols/group03/postgres_data"

networks:
  app_net:
    driver: overlay
